version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .nginx/cert.pem:/etc/cert.pem:ro
      - .nginx/key.pem:/etc/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main

  certbot-gen:
    container_name: certbot-gen
    build:
      context: .
      dockerfile: gen.dockerfile
    command: ["sh", "/generate-cert.sh"]
    env_file:
      - .env
    volumes:
      - .certbot/:/etc/letsencrypt/
      - ./scripts/generate-cert.sh:/generate-cert.sh
    networks:
      - main

  certbot-renew:
    container_name: certbot-renew
    build:
      context: .
      dockerfile: generate.dockerfile
    env_file:
      - .env
    networks:
      - main
    command: ["sh", "scripts/renew-cert.sh"]
    volumes:
      - .nginx/:/etc/nginx/
      - .certbot/:/etc/letsencrypt/
      - .logs/certbot.log:/var/log/letsencrypt:rw



networks:
  main:
    external: true