version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .certbot/live/certfolder/fullchain.pem:/etc/cert.pem:ro
      - .certbot/live/certfolder/privkey.pem:/etc/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main

  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: dockerfile
    command: ["sh", "/run-certbot.sh"]
    env_file:
      - .env
    volumes:
      - .certbot/:/etc/letsencrypt/
      - ./scripts/run-certbot.sh:/run-certbot.sh
    networks:
      - main

networks:
  main:
    external: true