version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    networks:
      - main
    ports:
      - "80:80"
      - "443:443"

  certbot:
    # image: certbot-alpine
    build:
      context: ./certbot
      dockerfile: Dockerfile
    container_name: certbot
    command: ["sh", "/scripts/generate-certificate-safe.sh"]
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
      - ./scripts:/scripts
      - ./backups:/backups
    networks:
      - main

networks:
  main:
    external: true
