version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .nginx/cert.pem:/etc/cert.pem:ro
      - .nginx/key.pem:/etc/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
  
  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    networks:
      - main
    command: ["sh", "scripts/generate-cert.sh"]
    volumes:
      - .nginx/:/etc/nginx/
      - .certbot/:/etc/letsencrypt/
      - .logs/certbot.log:/var/log/letsencrypt:rw

networks:
  main:
    external: true