version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.nginx/cert.pem:/etc/cert.pem:ro
      - ./.nginx/key.pem:/etc/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main

networks:
  main:
    external: true